### EDA and Feature Engineering - Flight Price Prediction

Check the dataset here:  
https://www.kaggle.com/datasets/shubhambathwal/flight-price-prediction

---

#### Features

The various features of the cleaned dataset are explained below:

1. **Airline** : The name of the airline company is stored in the airline column. It is a Categorical feature having 6 different airlines.

2. **Flight** : Flight stores information regarding the plane's flight code. It is a categorical feature. 

3. **Source City** : City from which the flight takes off. It is a categorical feature having 6 unique cities.

4. **Departure Time**  : This is a derived categorical feature obtained created by grouping time periods into bins. It stores information about the departure time and have 6 unique time labels.

5. **Stops** : A categorical feature with 3 distinct values that stores the number of stops between the source and destination cities.

6. **Arrival Time** : This is a derived categorical feature created by grouping time intervals into bins. It has six distinct time labels information about the arrival time.

7. **Destination City**  : City where the flight will land. It is categorical feature having 6 unique cities.

8. **Class** : A categorical feature that contains information on seat class; it has distinct values: Bussiness and Economy.

9. **Duration** : A continuous feature that display the overall amount of time it takes of travel between cities in hours.

10. **Days Left**  
    Number of days left before departure.  
    - Type: Numerical  

---

## Target Variable

- **Price**  
  The cost of the flight ticket.  
  - Type: Continuous (Regression Problem)

In [2]:
## importoing basic labraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df=pd.read_excel('002 flight-price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [5]:
##To display the last 5 rows of the dataframe
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [6]:
## Get basic info about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB